checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
tools:
    php_code_coverage: false
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]
filter:
    excluded_paths: [src/Event/, src/Lib/, tests, vendor, docs]
build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
